services:
  consumer:
    build: .
    ports:
      - "8081:8081"
    networks:
      - producer-consumer
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env_prod

networks:
  producer-consumer:
    external: true
