services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env_prod
    networks:
      - producer-consumer
    volumes:
      - postgres_data:/var/lib/postgresql/data

  consumer:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - producer-consumer
    env_file:
      - .env_prod

volumes:
  postgres_data:

networks:
  producer-consumer:
    external: true